version: '3.8'

services:
  chat-with-pdf:
    build: .
    container_name: chat-with-pdf-app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - LOG_LEVEL=INFO
    volumes:
      - ./data/pdfs:/app/data/pdfs
      - ./data/vectorstore:/app/data/vectorstore
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pdf_data:
  vector_data: 